name: home-manager build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - name: home-manager build
        run: nix build .#homeConfigurations.home.activationPackage
